### ISSUE TITLE
Difference between what test expects and instructions

### ISSUE THREAD

**Issue by jaf7** [learn-co-curriculum/oo-person#10]
In the instructions for the #call_friend method there is a difference between test expectations and instructions.
Test expects:
`convo = "Hi #{callee.name}! It's #{caller.name}. How are you?"`
Instructions say:
"Hi Felix. It's Stella! How are you?"
(Exclamation point after callee's name)

**Comment by morgvanny** [comment]
Thanks for the clarification! It should be fixed now.
