### ISSUE TITLE
slight typo

### ISSUE THREAD

**Issue by MenuDevelopment** [learn-co-curriculum/oo-person#11]
The call_friend method should accept another instance of the Person class, or "friend". The method should increment the caller and the callee's happiness points by three. If Stella calls her friend Felix, the method should return "Hi Felix. It's Stella! How are you?"

For this part, the readme specifies "Hi Felix. It's Stella! How are you?"
The test specifies "Hi Felix! It's Stella. How are you?"

**Comment by morgvanny** [comment]
Thanks! They should match now.
