### ISSUE TITLE
Warning when running tests

### ISSUE THREAD

**Issue by morgvanny** [learn-co-curriculum/oo-person#13]
Whether the lab is solved or not, this warning appears, due to an issue with one of the tests:

WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Actual error raised was #<NoMethodError: undefined method `name=' for #<Person:0x00007fc3d91ea790>
Did you mean?  name>. Instead consider providing a specific error class or message. This message can be suppressed by setting: `RSpec::Expectations.configuration.on_potential_false_positives = :nothing`. Called from /oo-person-dc-web-060418/spec/person_spec.rb:25:in `block (6 levels) in <top (required)>'.
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Actual error raised was #<NoMethodError: undefined method `name=' for #<Person:0x00007fc3d91ea6f0>
Did you mean?  name>. Instead consider providing a specific error class or message. This message can be suppressed by setting: `RSpec::Expectations.configuration.on_potential_false_positives = :nothing`. Called from /oo-person-dc-web-060418/spec/person_spec.rb:25:in `block (6 levels) in <top (required)>'.

This long message in the terminal can be confusing for students and distract them from actually reading the more important/relevant error messages and test output to solving the lab. I'm unsure of whether we want to change the test in order to heed the warning, or if we're ok with how it's functioning and want to instead take its advice on suppressing the warning.

**Comment by maxcell** [comment]
@morgvanny I totally just saw this error and didn't even know this issue was here! I'm gonna take some time and investigate what causes this. Let's double back on how to solve this!
